sudo: false
language: android
jdk: oraclejdk8
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=22
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - ANDROID_ABI=armeabi-v7a
   - ANDROID_TAG=google_apis
   - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL

    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
script:
        - ./gradlew build
        - ./gradlew clean build
        - ./gradlew assembleDebug
        - ./gradlew test
        - ./gradlew lint
        - ./gradlew assembleDebugAndroidTest
before_install:
          - mkdir "$ANDROID_HOME/licenses" || true
          - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
          - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
          - chmod +x gradlew
          - echo "sdk.dir=$ANDROID_HOME" > local.properties
branches:
        only:
                - master
